// ✅ Define types
export interface newsType {
  id: string;
  name: string;
  img: string;
  text: string;
  date: string;
  time: string | number;
  link: string;
  type: string; // e.g. AMA, DROP, AUCTION, etc.
}

export interface FilterOption {
  id: number;
  name: string;
}

// ✅ newss data
export const newss: newsType[] = [
  {
    id: '1',
    name: 'Revolutionary AI-Generated NFT Collection Launches',
    img: '/news/news.png',
    text: 'Discover how artificial intelligence is reshaping the NFT landscape with our latest collection featuring 10,000 unique pieces generated by cutting-edge algorithms.',
    date: 'October 10, 2025',
    time: '8',
    link: '/',
    type: 'FEATURED',
  },
  {
    id: '2',
    name: 'Behind the Canvas: An Interview with Digital Artist Maya Chen',
    img: '/news/news1.png',
    text: 'Explore the creative process and inspiration behind one of our most successful NFT collections with renowned digital artist Maya Chen.',
    date: 'October 8, 2025',
    time: '6',
    link: '/',
    type: 'ARTIST INTERVIEW',
  },
  {
    id: '3',
    name: 'New Marketplace Features: Enhanced Trading Experience',
    img: '/news/news2.png',
    text: 'Discover the latest updates to our trading platform including improved search filters and advanced analytics tools.',
    date: 'October 6, 2025',
    time: '4',
    link: '/',
    type: 'PRODUCT UPDATE',
  },
  {
    id: '4',
    name: 'Community Spotlight: Top Collectors of September',
    img: '/news/news3.png',
    text: 'Meet the passionate collectors who made significant contributions to our marketplace and community growth last month.',
    date: 'October 4, 2025',
    time: '5',
    link: '/',
    type: 'COMMUNITY',
  },
  {
    id: '5',
    name: 'Complete Guide: How to Create Your First NFT',
    img: '/news/news4.png',
    text: 'A comprehensive step-by-step tutorial for beginners to create, mint, and list their first NFT on our platform.',
    date: 'October 2, 2025',
    time: '10',
    link: '/',
    type: 'GUIDE',
  },
  {
    id: '6',
    name: 'Market Analytics Dashboard: Track Your Portfolio',
    img: '/news/news5.png',
    text: 'Introducing our new analytics dashboard that helps you track performance and make informed investment decisions.',
    date: 'September 30, 2025',
    time: '7',
    link: '/',
    type: 'PRODUCT UPDATE',
  },
  {
    id: '7',
    name: 'Exclusive Drop: The Future of Digital Art with Alex Rodriguez',
    img: '/news/news6.png',
    text: 'Get an inside look at the upcoming exclusive collection from visionary artist Alex Rodriguez and the future of digital art.',
    date: 'September 28, 2025',
    time: '9',
    link: '/',
    type: 'ARTIST INTERVIEW',
  },
  {
    id: '8',
    name: 'Exclusive Drop: The Future of Digital Art with Alex Rodriguez',
    img: '/news/news6.png',
    text: 'Get an inside look at the upcoming exclusive collection from visionary artist Alex Rodriguez and the future of digital art.',
    date: 'September 28, 2025',
    time: '9',
    link: '/',
    type: 'ARTIST INTERVIEW',
  },
];

// ✅ Filter categories
export const type: FilterOption[] = [
  { id: 1, name: 'All' },
  { id: 2, name: 'Product Updates' },
  { id: 3, name: 'Artist Interviews' },
  { id: 4, name: 'Community' },
  { id: 5, name: 'Guides' },
];
